[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "zabbixvms"
description = "Zabbix monitoring agent for Logic Elements VMS deployments"
version = "0.1.0"
authors = [
  { name="Jan Bartovský", email="jan.bartovsky@logicelements.cz" },
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
]
keywords = ["logicelements", "vibration", "vms", "zabbix"]

requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python",
    "jsonpickle",
    "zabbix_utils",
    "pywin32",
    "PyYAML",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
zabagent = ["data/*.json"]

[project.urls]
"Homepage" = "https://github.com/LogicElements/py-vms-zabbix"
